# Generated by Django 5.2.8 on 2026-03-10 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='keys',
            options={},
        ),
    ]
